// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlj7GoxkMwbXF3bcHQ6JL04eO4BKeTPRg',
    appId: '1:619671717747:web:570a8246a2f5eda0442706',
    messagingSenderId: '619671717747',
    projectId: 'totodo-shmr',
    authDomain: 'totodo-shmr.firebaseapp.com',
    storageBucket: 'totodo-shmr.appspot.com',
    measurementId: 'G-4DZQ7N22KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdCOynCyNiJZjcR8sS2xkte42U3jT_BVs',
    appId: '1:619671717747:android:6795595193216a8e442706',
    messagingSenderId: '619671717747',
    projectId: 'totodo-shmr',
    storageBucket: 'totodo-shmr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYEfxeKSHzKRjx3fqFDi4n1SD-njrKPYk',
    appId: '1:619671717747:ios:12947a889f9575cd442706',
    messagingSenderId: '619671717747',
    projectId: 'totodo-shmr',
    storageBucket: 'totodo-shmr.appspot.com',
    iosClientId: '619671717747-o9cjajgvesqcmrrau191mko0oikm58r1.apps.googleusercontent.com',
    iosBundleId: 'com.example.totodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYEfxeKSHzKRjx3fqFDi4n1SD-njrKPYk',
    appId: '1:619671717747:ios:12947a889f9575cd442706',
    messagingSenderId: '619671717747',
    projectId: 'totodo-shmr',
    storageBucket: 'totodo-shmr.appspot.com',
    iosClientId: '619671717747-o9cjajgvesqcmrrau191mko0oikm58r1.apps.googleusercontent.com',
    iosBundleId: 'com.example.totodo',
  );
}
