on:
  workflow_dispatch:
  push:
    branches:
      - main

name: "Build and Release for Android"

jobs:
  build:
    name: Build and Realse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter build apk -t lib/main_production.dart --dart-define=DEV=false
        timeout-minutes: 10
      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: build/app/outputs/apk/release/app-release.apk

    timeout-minutes: 10